name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Test CLI functionality
      run: |
        echo "blue" | npm run start
        echo "red" | npm run start
    
    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-staging:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/staging'
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Test CLI functionality
      run: |
        echo "blue" | npm run start
        echo "red" | npm run start
    
    - name: Publish to GitHub Packages with beta tag
      run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}